### ISSUE TITLE
Upgrading to OkHttp 4.0.0 

### ISSUE THREAD

**Issue by bizzguy** [andrzejchm/RESTMock#104]
I've upgraded my app to OkHttp 4.0.0 and I am no longer able to run RestMock tests.  The app crashes with this error:

    java.lang.NoSuchMethodError: No static method initializeInstanceForTests()V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/???-Erfx_-ETp-Rrby47elr7mg==/base.apk!classes34.dex)
        at okhttp3.mockwebserver.MockWebServer.<clinit>(MockWebServer.java:105)
        at io.appflate.restmock.RESTMockServer.init(RESTMockServer.java:70)
        at io.appflate.restmock.RESTMockServerStarter$1.run(RESTMockServerStarter.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by andrzejchm** [comment]
I'll update library with newest OkHttp version, thanks for reporting this!

**Comment by andrzejchm** [comment]
also, take a look here: https://github.com/andrzejchm/RESTMock/issues/81 if you happen to use proguard

**Comment by bizzguy** [comment]
I don't use proguard for the debug version which I use for testing.  But I will keep that in mind if I test my release version which does use proguard.

**Comment by andrzejchm** [comment]
@bizzguy 0.4.0 version got released and it includes OkHttp version 4.0.1 . this should solve the issue

**Comment by bizzguy** [comment]
That worked perfectly.  Thanks so much!
