### ISSUE TITLE
Upgrading to OkHttp 4.5.0

### ISSUE THREAD

**Issue by vsay01** [andrzejchm/RESTMock#111]
I've upgraded my app to OkHttp 4.5.0 and I am no longer able to run RestMock tests. The app crashes with this error:

`java.lang.NoSuchMethodError: No static method start$default(Lokhttp3/internal/http2/Http2Connection;ZILjava/lang/Object;)V in class Lokhttp3/internal/http2/Http2Connection; or its super classes (declaration of 'okhttp3.internal.http2.Http2Connection
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by andrzejchm** [comment]
Thanks for reporting! will bump the version of okHttp

**Comment by andrzejchm** [comment]
Could you please update to `0.4.3` version of this library and OkHttp to `4.6.0` and see if it works for you?

**Comment by vsay01** [comment]
@andrzejchm perfect. I upgrade both restMock and okHttp; now it's working fine.
