### ISSUE TITLE
Android P support

### ISSUE THREAD

**Issue by C2H6O** [andrzejchm/RESTMock#96]
Attempting to use this library with SDK 28 results in: 
```
java.lang.AssertionError: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for KeyPairGenerator.RSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at okhttp3.tls.HeldCertificate$Builder.generateKeyPair(HeldCertificate.java:429)
        at okhttp3.tls.HeldCertificate$Builder.build(HeldCertificate.java:353)
        at io.appflate.restmock.SslUtils.localhost(SslUtils.java:44)
        at io.appflate.restmock.RESTMockServer.setUpHttps(RESTMockServer.java:91)
        at io.appflate.restmock.RESTMockServer.init(RESTMockServer.java:74)
```

I'm assuming that switching over to a different keyAlgorithm will work. Thoughts?

**Comment by andrzejchm** [comment]
problem is related to generation of the certificates in OkHttp and was fixed here: https://github.com/square/okhttp/issues/4443 but there was not yet an official release of OkHttp with that fix. You can use the newest development version of okHttp library in your project though, overriding the one provided with RESTMock:

Specify this in your app's `build.gradle`
```groovy
..
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

configurations.all {
    resolutionStrategy {
        force "com.squareup.okhttp3:okhttp:3.13.0-SNAPSHOT"
        force "com.squareup.okhttp3:okhttp-tls:3.13.0-SNAPSHOT"
        force "com.squareup.okhttp3:mockwebserver:3.13.0-SNAPSHOT"
        force "com.squareup.okhttp3:logging-interceptor:3.13.0-SNAPSHOT"
    }
}
```
